In [2]:
# import numpy

import numpy as np

In [3]:
myls= [1,2,3]

In [5]:
# we can cast the list to an array

arr= np.array(myls)

In [7]:
arr

array([1, 2, 3])

In [8]:
# we can create a matrix out of this
mymat = [[1,2,3],[4,5,6],[7,8,9]]

np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# use the numpy version of python's range function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
# remmeber the ones and zeros functions from matlab

In [17]:
type(np.ones(3)[1])
    

numpy.float64

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
# You can also make the identity matrix

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
# we can also get matrix of random numbers
np.random.rand(2,2)

array([[0.8467924 , 0.26717638],
       [0.09293239, 0.45519207]])

In [46]:
# We can also generate an amount of random integers in a certain non-inclusive range
np.random.randint(1,20,10)

array([10, 12,  2,  6,  3,  4,  4, 12, 13,  4])

In [47]:
# You can create an array of numbers up to a certain limit using the arange method.
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
# You can reshape an array using the reshape method

arr.reshape(5,5)

# BE WARNED you need an array size that will match the length or dimensions of the array.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
# Arrays have a min and max method
arr.min()

0

In [54]:
arr.max()

24

In [56]:
# You can find the locations of the min and max through the argmin and argmax methods
arr.argmin()

0

In [57]:
arr.argmax()

24

In [59]:
# To find an array's shape you can use the shape attribute
arr.shape

(25,)

In [61]:
# To find the type of the elements stored in the array use dtype
arr.dtype

dtype('int32')