In [2]:
# Remember MatLab vectors and arrays and list from normal Python?

import numpy as np

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# check index 8
arr[8]

8

In [8]:
# check indicies 0 through 5
# Rememeber that  the upper limit is non-inclusive
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
# arrays can also broadcast, unlike lists
slice_of_array =  arr[0:6]

In [11]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [12]:
# Doing this will alter the original array and not make a copy
slice_of_array[:] = 99

In [13]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [16]:
# If you want to make a copy of the array use the copy method
arr_copy = arr.copy()

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [18]:
arr_copy[:] = 100

In [19]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [23]:
# Now Let's practice indexing a matrix instead of vector arrays
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
# A single bracket indexes a row
arr_2d[0]

array([ 5, 10, 15])

In [32]:
# Using a comma in the brackets splits the rows and columns
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
# lets pick row 2 , column 2
arr_2d[1,1]

25

In [35]:
# now let's try logical indexing
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# Create a boolean array of where each element is greater than 60

bool_arr = arr >5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [37]:
# now use the boolean array as indicies of the original array
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [39]:
# you can also just index using the logical operator
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr==2]

array([2])

In [43]:
arr_2d =  np.arange(0,50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])